version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/app/dist

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=hono_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - FRONTEND_BUILD_DIR=/frontend_dist
    depends_on:
      - postgres
      - frontend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - frontend_build:/frontend_dist
    command: bun run dev

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hono_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  frontend_build:
