services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    volumes:
      - ./backend/admin/dist:/app/admin/dist  # Mount admin build to backend container
      - ./backend/src:/app/src                 # Backend source code
      - ./backend/package.json:/app/package.json
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hono_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
